'use strict';
const $ = id => document.getElementById(id);
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = value => new Intl.NumberFormat('ko-KR').format(value);
const reasons = {APPROVED:'모든 승인 조건을 충족했습니다.',NOT_SUBMITTED:'아직 제출되지 않은 요청입니다.',REVIEWER_INACTIVE:'검토자가 비활성 상태입니다.',SELF_APPROVAL:'요청자 본인의 승인은 허용되지 않습니다.',TEAM_MISMATCH:'요청자와 검토자의 팀이 다릅니다.',OVER_LIMIT:'요청 금액이 승인 한도를 초과했습니다.'};
const rules = [['same_team','같은 팀만 승인','요청 팀과 검토 팀 일치'],['active_reviewer','활성 검토자 필수','비활성 검토자의 승인 제한'],['prevent_self','본인 승인 방지','요청자와 검토자 분리']];
let receipt = null, source = null, codeTab = 'gooo', busy = false, suiteBusy = false, history = [], toastTimer;
try { const stored=JSON.parse(localStorage.getItem('gooo-policy-history-v1')||'[]'); if(Array.isArray(stored)) history=stored.filter(r=>r?.schema==='policy-studio/execution/v1'&&r.input?.request&&r.result?.before&&r.result?.after).slice(0,30); } catch {}
for(const side of ['before','after']) $(''+side+'-rules').innerHTML=rules.map(([key,title,desc])=>`<label class="rule" for="${side}-${key}"><span><strong>${title}</strong><small>${desc}</small></span><input class="switch" id="${side}-${key}" type="checkbox" checked aria-label="${side==='before'?'현재':'변경'} 정책: ${title}"></label>`).join('');
function toast(message,error=false){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.toggle('error',error);$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,5000);}
function showView(view){for(const name of ['studio','history','source']) $(name+'-view').hidden=name!==view;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('breadcrumb').textContent={studio:'정책 시뮬레이터',history:'실행 기록',source:'소스 & 실행 근거'}[view];if(view==='history')renderHistory();if(view==='source')loadSource();window.scrollTo({top:0});}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
function policy(side){return {limit:Number($(side+'-limit').value),same_team:$(side+'-same_team').checked,active_reviewer:$(side+'-active_reviewer').checked,prevent_self:$(side+'-prevent_self').checked};}
function input(){return {request:{key:$('request-key').value.trim(),requester:$('requester').value.trim(),team:$('request-team').value.trim(),amount:Number($('amount').value),submitted:$('submitted').checked},reviewer:{key:$('reviewer-key').value.trim(),team:$('reviewer-team').value.trim(),active:$('reviewer-active').checked},before:policy('before'),after:policy('after')};}
function valid(){return $('policy-form').reportValidity()&&$('request-form').reportValidity();}
async function api(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const body=await r.json();if(!r.ok)throw Error(body.error||'실행에 실패했습니다.');return body;}
function invalidate(){receipt=null;$('download').disabled=true;$('result').className='empty-state';$('result').innerHTML='<span class="empty-icon">⇄</span><h3>입력이 변경됐습니다.</h3><p>정책 비교를 실행해 현재 값의 결과를 확인하세요.</p>';}
function invalidateSuite(){$('suite').innerHTML='<div class="quiet-empty">정책이 변경됐습니다. 사례 비교를 다시 실행하세요.</div>';}
$('policy-form').addEventListener('input',()=>{invalidate();invalidateSuite();});$('request-form').addEventListener('input',invalidate);
function save(r){history=[r,...history.filter(h=>h.id!==r.id)].slice(0,30);try{localStorage.setItem('gooo-policy-history-v1',JSON.stringify(history));}catch{toast('실행은 완료됐지만 브라우저 기록 저장에 실패했습니다.',true);}$('history-count').textContent=history.length;}
function render(r){const {before,after,change}=r.result;const item=r.input.request;
 $('result').className='result-content';
 const label=change.direction==='NEWLY_APPROVED'?'거절 → 승인':change.direction==='NEWLY_DENIED'?'승인 → 거절':change.reason_changed?'승인 상태 동일 · 이유 변경':'판단 유지';
 $('result').innerHTML=`<div class="result-summary"><div><h3>${esc(item.key)} <span class="crumb">·</span> ₩${money(item.amount)}</h3><p>${esc(item.requester)} · ${esc(item.team)} / 검토자 ${esc(r.input.reviewer.key)}</p></div><span class="impact">${label}</span></div><div class="outcomes">${[['현재 정책',before],['변경할 정책',after]].map(([name,d])=>`<article class="outcome"><small>${name}</small><div class="decision ${d.approved?'approved':'denied'}">${d.approved?'승인 가능 ↗':'승인 거절'}</div><p>${esc(reasons[d.reason]||d.reason)}</p></article>`).join('')}</div><table class="trace-table"><thead><tr><th scope="col">Gooo 규칙 관측</th><th scope="col">현재 정책</th><th scope="col">변경할 정책</th></tr></thead><tbody>${[['submitted_ok','요청 제출'],['reviewer_ok','검토자 활성 조건'],['self_ok','자기 승인 제한'],['team_ok','팀 일치 조건'],['amount_ok','금액 한도']].map(([key,title])=>`<tr><td>${title}</td>${[before,after].map(d=>`<td class="${d[key]?'ok':'fail'}">${d[key]?'✓ 통과':'× 미충족'}</td>`).join('')}</tr>`).join('')}</tbody></table><div class="receipt-foot">규칙을 비활성화하면 해당 조건은 통과합니다. 거절 이유는 제출 → 활성 → 자기 승인 → 팀 → 금액 순으로 선택합니다.<br>실행 ${esc(new Date(r.created_at).toLocaleString('ko-KR'))} · 근거 ${esc(r.id)}<br>소스 ${esc(r.source_sha256)}<br>실행한 두 정책과 이 요청에 대한 관측입니다. 전체 입력에 대한 증명은 아닙니다.</div>`;
 receipt=r;$('download').disabled=false;
}
$('policy-form').addEventListener('submit',async e=>{e.preventDefault();if(busy||!valid())return;const snapshot=input();busy=true;$('run').disabled=true;$('run').textContent='Gooo 실행 중…';try{const r=await api('/api/simulate',snapshot);save(r);if(JSON.stringify(input())===JSON.stringify(snapshot)){render(r);toast('두 정책을 실행했습니다.');}else toast('입력이 변경됐습니다. 이전 입력의 실행은 기록에 보관했습니다.');}catch(err){toast(err.message,true);}finally{busy=false;$('run').disabled=false;$('run').innerHTML='정책 비교 실행 <span>→</span>';}});
$('request-form').addEventListener('submit',e=>{e.preventDefault();$('policy-form').requestSubmit();});
function resetRequest(){for(const [id,value] of Object.entries({'request-key':'REQ-2026-042',requester:'김민수','request-team':'제품팀',amount:750000,'reviewer-key':'이지원','reviewer-team':'제품팀'}))$(id).value=value;$('submitted').checked=true;$('reviewer-active').checked=true;}
$('reset').addEventListener('click',()=>{$('before-limit').value=500000;$('after-limit').value=1000000;for(const side of ['before','after'])for(const [key] of rules)$(side+'-'+key).checked=true;resetRequest();invalidate();invalidateSuite();});
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{resetRequest();switch(b.dataset.preset){case 'team':$('reviewer-team').value='운영팀';break;case 'self':$('reviewer-key').value='김민수';break;case 'inactive':$('reviewer-active').checked=false;break;case 'draft':$('submitted').checked=false;break;}invalidate();}));
function download(data,name,type='application/json'){const blob=new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('download').addEventListener('click',()=>{if(receipt)download(receipt,'gooo-policy-receipt.json');});
function scenarios(before,after){const base={request:{key:'CASE',requester:'김민수',team:'제품팀',amount:100000,submitted:true},reviewer:{key:'이지원',team:'제품팀',active:true},before,after};const definitions=[['기본 승인',{}],['현재 한도 바로 아래',{amount:Math.max(0,before.limit-1)}],['현재 한도 일치',{amount:before.limit}],['현재 한도 바로 위',{amount:Math.min(9000000000000,before.limit+1)}],['변경 한도 일치',{amount:after.limit}],['변경 한도 바로 위',{amount:Math.min(9000000000000,after.limit+1)}],['0원 요청',{amount:0}],['다른 팀 검토',{}, {team:'운영팀'}],['비활성 검토자',{}, {active:false}],['본인 승인',{}, {key:'김민수'}],['미제출 요청',{submitted:false}],['여러 조건 미충족',{submitted:false,amount:9000000000000},{key:'김민수',team:'운영팀',active:false}]];return definitions.map(([name,req={},rev={}],i)=>({name,input:{...base,request:{...base.request,...req,key:`CASE-${String(i+1).padStart(2,'0')}`},reviewer:{...base.reviewer,...rev}}}));}
$('run-suite').addEventListener('click',async()=>{if(suiteBusy||!$('policy-form').reportValidity())return;suiteBusy=true;$('run-suite').disabled=true;$('run-suite').textContent='12개 사례 실행 중…';const before=policy('before'),after=policy('after');try{const rows=[];for(const s of scenarios(before,after))rows.push({...s,receipt:await api('/api/simulate',s.input)});if(JSON.stringify([before,after])!==JSON.stringify([policy('before'),policy('after')])){toast('정책이 바뀌었습니다. 사례 비교를 다시 실행하세요.');return;}const changed=rows.filter(r=>r.receipt.result.change.changed).length;const approved=rows.filter(r=>r.receipt.result.after.approved).length;$('suite').innerHTML=`<div class="suite-summary"><span><strong>12</strong> 실행 사례</span><span><strong>${changed}</strong> 승인 상태 변경</span><span><strong>${approved}</strong> 변경 정책 승인</span></div><div class="table-scroll"><table class="suite-table"><thead><tr><th>사례</th><th>금액</th><th>현재</th><th>변경</th><th>결과</th><th></th></tr></thead><tbody>${rows.map((s,i)=>`<tr><td>${esc(s.name)}</td><td>₩${money(s.input.request.amount)}</td><td>${s.receipt.result.before.approved?'승인':'거절'}</td><td>${s.receipt.result.after.approved?'승인':'거절'}</td><td class="${s.receipt.result.change.changed?'ok':''}">${s.receipt.result.change.changed?'변경':'유지'}</td><td><button data-case="${i}">상세 ↗</button></td></tr>`).join('')}</tbody></table></div>`;$('suite').querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>{const r=rows[Number(b.dataset.case)].receipt;applyInput(r.input);save(r);render(r);$('result').scrollIntoView({block:'center',behavior:'smooth'});}));toast('12개 사례의 실제 실행 결과를 비교했습니다.');}catch(err){toast(err.message,true);}finally{suiteBusy=false;$('run-suite').disabled=false;$('run-suite').textContent='12개 사례 비교 ↗';}});
function applyInput(inData){for(const side of ['before','after']){$(side+'-limit').value=inData[side].limit;for(const [key] of rules)$(side+'-'+key).checked=inData[side][key];}for(const [id,v]of Object.entries({'request-key':inData.request.key,requester:inData.request.requester,'request-team':inData.request.team,amount:inData.request.amount,'reviewer-key':inData.reviewer.key,'reviewer-team':inData.reviewer.team}))$(id).value=v;$('submitted').checked=inData.request.submitted;$('reviewer-active').checked=inData.reviewer.active;}
function renderHistory(){$('history-count').textContent=history.length;$('history-list').innerHTML=history.length?history.map((r,i)=>`<article class="card history-item"><div><h3>${esc(r.input.request.key)} · ₩${money(r.input.request.amount)}</h3><p>${esc(new Date(r.created_at).toLocaleString('ko-KR'))} · ${r.result.before.approved?'승인':'거절'} → ${r.result.after.approved?'승인':'거절'}<br>${esc(r.id?.slice(0,31))}…</p></div><div class="history-actions"><button class="button small" data-replay="${i}">재실행 ↺</button><button class="button small" data-export="${i}">JSON ↓</button></div></article>`).join(''):'<div class="card empty-state"><h3>아직 실행 기록이 없습니다.</h3><p>정책 비교를 실행하거나 JSON 기록을 가져오세요.</p></div>';$('history-list').querySelectorAll('[data-export]').forEach(b=>b.addEventListener('click',()=>download(history[Number(b.dataset.export)],'gooo-policy-receipt.json')));$('history-list').querySelectorAll('[data-replay]').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;try{await replay(history[Number(b.dataset.replay)]);}finally{b.disabled=false;}}));}
async function replay(r){try{const out=await api('/api/replay',r);applyInput(out.receipt.input);invalidateSuite();save(out.receipt);render(out.receipt);showView('studio');toast('소스·생성 코드와 실행 결과가 일치합니다.');}catch(err){toast(err.message,true);}}
$('import-receipt').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>128*1024)throw Error('128KB 이하의 실행 기록만 가져올 수 있습니다.');await replay(JSON.parse(await file.text()));}catch(err){toast(err.message,true);}finally{e.target.value='';}});
$('clear-history').addEventListener('click',()=>{history=[];try{localStorage.removeItem('gooo-policy-history-v1');}catch{}renderHistory();toast('이 브라우저의 실행 기록을 지웠습니다.');});
async function loadSource(){if(!source){try{const r=await fetch('/api/source');if(!r.ok)throw Error('소스를 불러오지 못했습니다.');source=await r.json();}catch(err){$('source-code').textContent=err.message;return;}}renderSource();}
function renderSource(){$('source-code').textContent=codeTab==='generation'?JSON.stringify(source.generation,null,2):source[codeTab];document.querySelectorAll('[data-code]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.code===codeTab)));}
document.querySelectorAll('[data-code]').forEach(b=>b.addEventListener('click',()=>{codeTab=b.dataset.code;if(source)renderSource();}));
$('download-source').addEventListener('click',()=>{if(source)download(codeTab==='generation'?source.generation:source[codeTab],{gooo:'approval.gooo',go:'rules_generated.go',generation:'generation.json'}[codeTab],codeTab==='generation'?'application/json':'text/plain;charset=utf-8');});
$('history-count').textContent=history.length;
